### ISSUE TITLE
This is not working on my server.

### ISSUE THREAD

**Issue by Stormsns** [Slivicon/StartMeUp#2] opened 2018-03-05 14:32 UTC
My understanding of the mod is that it is suppose to allow each player the option to have automatic motor start/stop on or off. It works great with just one player on the server, but when others get on the server, it seems to have a mind of it's own. If I have mine set to automatically start/stop when entering or leaving vehicle and a friend comes in the server and changes his to manually start/stop when he enters or leaves his vehicle, I have to manually start/stop my vehicle. It's like when some one changes it, it sets it serverwide and not individually.

Thanks

**Comment by Slivicon** [comment] 2018-03-05 14:56
Is this with the latest version, 2.0.0.1 on a dedicated server?

**Comment by Stormsns** [comment] 2018-03-05 15:00
Yes.

<modDesc descVersion="38">
    <author>Slivicon</author>
    <version>2.0.0.1</version>
    <title>
      <de>StartMeUp</de>
      <en>StartMeUp</en>
      <fr>StartMeUp</fr>
    </title>
    <description>

**Comment by Slivicon** [comment] 2018-03-05 15:07
OK, thank you I will test again to see if I can replicate your issue.

**Comment by Slivicon** [comment] 2018-03-05 17:25
Please try the new v2.0.0.2 zip here https://github.com/Slivicon/StartMeUp/releases/download/v2.0.0.2/FS17_StartMeUp.zip which has a fix for the bug and let me know if the issue is fixed for you.

**Comment by Stormsns** [comment] 2018-03-05 20:17
Ok, this version 2.0.0.2 fixed the issue we were having. It works as advertised now.

Thank you very much!

**Comment by Slivicon** [comment] 2018-03-05 20:57
fixed in commit 09a4d1a5e692c5538bfbabdb35787c52756c0ae0

**Closed as completed by Slivicon** 2018-03-05 20:57 UTC
Labels: bug
